using System.Text.Json.Serialization;
using Aesir.Common.Prompts;

namespace Aesir.Common.Models;

/// <summary>
/// Represents a chat message within the Aesir system.
/// </summary>
public class AesirChatMessage : IEquatable<AesirChatMessage>
{
    /// <summary>
    /// Gets or sets the role of the participant in the chat message (e.g., "user", "assistant", "system").
    /// </summary>
    [JsonPropertyName("role")]
    public string Role { get; set; } = null!;

    /// <summary>
    /// Gets or sets the content of the message. This may include plain text, formatted content, or embedded file references.
    /// </summary>
    [JsonPropertyName("content")]
    public string Content { get; set; } = null!;

    [JsonPropertyName("thoughts_content")]
    public string? ThoughtsContent { get; set; }

    /// <summary>
    /// Gets or sets the tool calls made during generation of this message.
    /// Only populated for assistant messages.
    /// </summary>
    [JsonPropertyName("tool_calls")]
    public IReadOnlyList<AesirToolCallInfo>? ToolCalls { get; set; }

    /// <summary>
    /// Gets or sets the research session ID for research team messages.
    /// When set, indicates this message was generated by a research team.
    /// </summary>
    [JsonPropertyName("research_session_id")]
    public Guid? ResearchSessionId { get; set; }

    /// <summary>
    /// Gets or sets the research team ID for research team messages.
    /// When set, indicates this message was generated by a research team.
    /// </summary>
    [JsonPropertyName("research_team_id")]
    public Guid? ResearchTeamId { get; set; }

    /// <summary>
    /// Gets or sets the research team name for research team messages.
    /// </summary>
    [JsonPropertyName("research_team_name")]
    public string? ResearchTeamName { get; set; }

    /// <summary>
    /// Gets or sets when the message was created (UTC).
    /// Nullable to handle migration of existing data without timestamps.
    /// </summary>
    [JsonPropertyName("created_at")]
    public DateTimeOffset? CreatedAt { get; set; }
    
    /// <summary>
    /// Determines if the message content contains a file reference.
    /// </summary>
    /// <returns>True if the content includes a file reference; otherwise, false.</returns>
    public bool HasFile()
    {
        if (Role != "user") return false;
        
        // Use regex to detect <file>...</file> pattern anywhere in the content
        return System.Text.RegularExpressions.Regex.IsMatch(
            Content, 
            @"<file>.*?</file>", 
            System.Text.RegularExpressions.RegexOptions.IgnoreCase);

    }

    /// <summary>
    /// Adds a file reference to the content of the message. Supports multiple files.
    /// </summary>
    /// <param name="filename">The name of the file to be added to the content.</param>
    public void AddFile(string filename)
    {
        if (Role != "user") return;

        // Always prepend the file tag (supports multiple files)
        Content = $"<file>{filename}</file>{Content}";
    }

    /// <summary>
    /// Extracts the first file name from the message content if a file tag is present.
    /// For multiple files, use GetFileNames().
    /// </summary>
    /// <returns>The extracted file name if a file tag exists; otherwise, null.</returns>
    public string? GetFileName()
    {
        var fileNames = GetFileNames();
        return fileNames.Count > 0 ? fileNames[0] : null;
    }

    /// <summary>
    /// Extracts all file names from the message content.
    /// </summary>
    /// <returns>A list of file names found in the message content.</returns>
    public IReadOnlyList<string> GetFileNames()
    {
        if (Role != "user" || !HasFile())
            return Array.Empty<string>();

        var matches = System.Text.RegularExpressions.Regex.Matches(
            Content,
            @"<file>(.*?)</file>",
            System.Text.RegularExpressions.RegexOptions.IgnoreCase);

        return matches.Select(m => m.Groups[1].Value).ToList();
    }

    /// <summary>
    /// Gets the message content with file references removed and formats it for display.
    /// </summary>
    /// <returns>The message content with all file references stripped, formatted for display.</returns>
    public string? GetContentWithoutFileName()
    {
        if (Role != "user" || !HasFile()) return Content;

        // Use regex to remove all <file>...</file> tags
        var result = System.Text.RegularExpressions.Regex.Replace(
            Content, 
            @"<file>.*?</file>", 
            string.Empty, 
            System.Text.RegularExpressions.RegexOptions.IgnoreCase);
    
        // Clean up any extra whitespace that might be left
        return result.Trim();
    }

    /// <summary>
    /// Gets the message content with file references included and formatted for display.
    /// Supports multiple files.
    /// </summary>
    /// <returns>The message content with file references included and formatted for display.</returns>
    public string? GetContentWithFileName()
    {
        if (Role != "user" || !HasFile()) return Content;

        // Use regex to remove all <file>...</file> tags
        var result = System.Text.RegularExpressions.Regex.Replace(
            Content,
            @"<file>.*?</file>",
            string.Empty,
            System.Text.RegularExpressions.RegexOptions.IgnoreCase);

        result = result.Trim();

        // Format all files for the LLM
        var fileNames = GetFileNames();
        if (fileNames.Count == 1)
        {
            result = $"The file is: {fileNames[0]}\n{result}";
        }
        else if (fileNames.Count > 1)
        {
            var fileList = string.Join(", ", fileNames);
            result = $"The files are: {fileList}\n{result}";
        }

        // Clean up any extra whitespace that might be left
        return result.Trim();
    }

    /// <summary>
    /// Normalizes the content string by trimming whitespace, removing outer HTML tags,
    /// and processing any additional formatting to simplify the content structure.
    /// </summary>
    /// <param name="content">The original content string to be normalized.</param>
    /// <returns>The normalized content string, with unnecessary outer HTML tags removed and trimmed whitespace.</returns>
    private static string NormalizeContent(string content)
    {
        if (string.IsNullOrWhiteSpace(content))
            return content;

        var trimmedContent = content.Trim();
    
        // Check if the content is wrapped in HTML tags
        if (trimmedContent.StartsWith("<") && trimmedContent.EndsWith(">"))
        {
            // Find the first opening tag
            var firstTagEnd = trimmedContent.IndexOf('>');
            if (firstTagEnd > 0)
            {
                var openingTag = trimmedContent.Substring(0, firstTagEnd + 1);
            
                // Extract tag name (e.g., "p" from "<p>" or "<p class='test'>")
                var tagNameMatch = System.Text.RegularExpressions.Regex.Match(openingTag, @"<(\w+)");
                if (tagNameMatch.Success)
                {
                    var tagName = tagNameMatch.Groups[1].Value;
                    var closingTag = $"</{tagName}>";
                
                    // Check if content ends with the corresponding closing tag
                    if (trimmedContent.EndsWith(closingTag, StringComparison.OrdinalIgnoreCase))
                    {
                        // Remove the outermost container tags
                        var innerContent = trimmedContent.Substring(firstTagEnd + 1, 
                            trimmedContent.Length - firstTagEnd - 1 - closingTag.Length);
                    
                        // Recursively check for more outer containers
                        return NormalizeContent(innerContent);
                    }
                }
            }
        }
    
        // If no outer container found, just replace newlines
        return trimmedContent;
    }

    /// <summary>
    /// Creates a new system message with the specified content and context.
    /// </summary>
    /// <param name="promptPersona">The PromptPerson to use. If null, uses Business</param>
    /// <param name="customContent">The optional content of the system message if the PromptPerson is Custom.</param>
    /// <returns>A new instance of <see cref="AesirChatMessage"/> configured as a system message.</returns>
    public static AesirChatMessage NewSystemMessage(PromptPersona? promptPersona, string? customContent = null)
    {
        var content = "";
        
        if (promptPersona == PromptPersona.Custom)
        {
            if (string.IsNullOrEmpty(customContent))
                throw new InvalidOperationException("Missing custom content");
            
            content = customContent;
        }
        else
        {
            var promptProvider = DefaultPromptProvider.Instance;

            if (promptPersona == null)
                content = promptProvider.GetSystemPrompt(PromptPersona.Business).Content;
            else
                content = promptProvider.GetSystemPrompt(promptPersona.Value).Content;
        }

        return new AesirChatMessage()
        {
            Role = "system",
            Content = content,
            CreatedAt = DateTimeOffset.UtcNow
        };
    }

    /// <summary>
    /// Creates a new message with the role of 'assistant' and assigns the specified content to it.
    /// </summary>
    /// <param name="content">The content of the assistant's message.</param>
    /// <returns>A new instance of <see cref="AesirChatMessage"/> representing an assistant message with the specified content.</returns>
    public static AesirChatMessage NewAssistantMessage(string content)
    {
        return new AesirChatMessage()
        {
            Role = "assistant",
            Content = content,
            CreatedAt = DateTimeOffset.UtcNow
        };
    }

    /// <summary>
    /// Creates a new user message with the specified content.
    /// </summary>
    /// <param name="content">The content of the user message.</param>
    /// <returns>A new instance of <see cref="AesirChatMessage"/> representing a user message.</returns>
    public static AesirChatMessage NewUserMessage(string content)
    {
        return new AesirChatMessage()
        {
            Role = "user",
            Content = NormalizeContent(content),
            CreatedAt = DateTimeOffset.UtcNow
        };
    }

    /// <summary>
    /// Creates a new research team message with the specified content.
    /// </summary>
    /// <param name="content">The content of the research team message (typically the report or status).</param>
    /// <param name="sessionId">The research session ID.</param>
    /// <param name="teamId">The research team ID.</param>
    /// <param name="teamName">The research team name.</param>
    /// <returns>A new instance of <see cref="AesirChatMessage"/> representing a research team message.</returns>
    public static AesirChatMessage NewResearchTeamMessage(
        string content,
        Guid sessionId,
        Guid teamId,
        string teamName)
    {
        return new AesirChatMessage()
        {
            Role = "assistant",
            Content = content,
            ResearchSessionId = sessionId,
            ResearchTeamId = teamId,
            ResearchTeamName = teamName,
            CreatedAt = DateTimeOffset.UtcNow
        };
    }

    /// <summary>
    /// Checks if this message is a research team message.
    /// Research team messages are identified by having a ResearchTeamId set.
    /// </summary>
    public bool IsResearchTeamMessage => ResearchTeamId.HasValue;

    /// <summary>
    /// Determines whether the specified AesirChatMessage is equal to the current instance.
    /// </summary>
    /// <param name="other">The AesirChatMessage to compare with the current instance.</param>
    /// <returns><c>true</c> if the specified message is equal to the current instance; otherwise, <c>false</c>.</returns>
    public bool Equals(AesirChatMessage? other)
    {
        if (other is null) return false;
        if (ReferenceEquals(this, other)) return true;
        return Role == other.Role && Content == other.Content;
    }

    /// <summary>
    /// Determines whether the specified object is equal to the current instance.
    /// </summary>
    /// <param name="obj">The object to compare with the current instance.</param>
    /// <returns>True if the specified object is equal to the current instance; otherwise, false.</returns>
    public override bool Equals(object? obj)
    {
        if (obj is null) return false;
        if (ReferenceEquals(this, obj)) return true;
        if (obj.GetType() != GetType()) return false;
        return Equals((AesirChatMessage)obj);
    }

    /// <summary>
    /// Serves as the default hash function for the AesirChatMessage class by combining its Role and Content properties.
    /// </summary>
    /// <returns>A hash code for the current AesirChatMessage instance.</returns>
    public override int GetHashCode()
    {
        return HashCode.Combine(Role, Content);
    }
}