volumes:
  dbdata:
  letsencryptdata:
  qdrant_storage:

services:
  aesir:
    image: aesir.api.server
    build:
      context: .
      dockerfile: Aesir.Api.Server/Dockerfile
    depends_on:
      pgdb:
        condition: service_healthy
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    healthcheck:
      test: [ "CMD", "curl", "--fail", "http://aesir/healthz" ]
      interval: 10s
      timeout: 5s
      retries: 10
    labels:
      - "traefik.enable=true"
      # HTTP Router
      - "traefik.http.routers.aesir-http.rule=Host(`aesir.localhost`)"
      - "traefik.http.routers.aesir-http.entrypoints=web"
      - "traefik.http.routers.aesir-http.service=aesir"
      # HTTPS Router
      - "traefik.http.routers.aesir-https.rule=Host(`aesir.localhost`)"
      - "traefik.http.routers.aesir-https.entrypoints=websecure"
      - "traefik.http.routers.aesir-https.tls=true"
      - "traefik.http.routers.aesir-https.tls.certresolver=letsencryptresolver"
      - "traefik.http.routers.aesir-https.service=aesir"
      # Service definition
      - "traefik.http.services.aesir.loadbalancer.server.port=80"

  pgdb:
    environment:
      POSTGRES_PASSWORD: RaGn4r0k!!
    image: pgvector/pgvector:pg16
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 10
    labels:
      - "traefik.enable=false"

  reverse-proxy:
    image: traefik:latest
    restart: unless-stopped
    depends_on:
      pgdb:
        condition: service_healthy
    command:
      - "--log.level=DEBUG"
      - "--accesslog=true"
      - "--providers.docker.exposedbydefault=false"
      - "--api.insecure=true"
      - "--api.debug=true"
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.letsencryptresolver.acme.email=info@ronin.consulting"
      - "--certificatesresolvers.letsencryptresolver.acme.storage=/letsencrypt/acme.json"
      - "--certificatesresolvers.letsencryptresolver.acme.httpchallenge=true" # Changed to true for Let's Encrypt
      - "--certificatesresolvers.letsencryptresolver.acme.httpchallenge.entrypoint=web"
    ports:
      - "443:443"
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - letsencryptdata:/letsencrypt

  qdrant:
    image: qdrant/qdrant:latest
    restart: always
    container_name: qdrant
    environment:
      - QDRANT__SERVICE__API_KEY=aesir_3a087fa5640958985025b0a03d2f6b0c80253884c5bd7c05f65f2fdf2404d7ab
    ports:
      - 6333:6333
      - 6334:6334
    expose:
      - 6333
      - 6334
      - 6335
    configs:
      - source: qdrant_config
        target: /qdrant/config/production.yaml
    volumes:
      - qdrant_storage:/qdrant/storage
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.qdrant.rule=Host(`qdrant.localhost`)"
      - "traefik.http.routers.qdrant.entrypoints=web"
      - "traefik.http.routers.qdrant.entrypoints=websecure"
      - "traefik.http.routers.qdrant.tls=true"
      - "traefik.http.routers.qdrant.tls.certresolver=letsencryptresolver"
      - "traefik.http.services.qdrant.loadbalancer.server.port=6333"

configs:
  qdrant_config:
    content: |
      log_level: INFO