version: '3.8'

services:
  aesir-client-desktop:
    build:
      context: .
      dockerfile: Aesir.Client/Aesir.Client.Desktop/Dockerfile
      platforms:
        - linux/amd64
        - linux/arm64
    container_name: aesir-client-desktop
    environment:
      - DISPLAY=${DISPLAY:-:0}
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      # X11 socket for GUI forwarding
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      # Optional: Mount config directory for persistence
      - ./config:/app/config
      # Optional: Mount logs directory
      - ./logs:/app/logs
    networks:
      - aesir-network
    depends_on:
      - aesir-api
    restart: unless-stopped
    # Uncomment if you need to override the default command
    # command: dotnet Aesir.Client.Desktop.dll

  # Add the API service if not already defined elsewhere
  aesir-api:
    build:
      context: .
      dockerfile: Aesir.Api.Server/Dockerfile
    container_name: aesir-api-server
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5000:8080"
    networks:
      - aesir-network
    restart: unless-stopped

networks:
  aesir-network:
    driver: bridge

volumes:
  config:
  logs: