namespace Aesir.Api.Server.Services.Implementations.Standard;

/// <summary>
/// Class for generating unique keys of type <typeparamref name="TKey"/>.
/// </summary>
/// <typeparam name="TKey">
/// The type of the keys to be generated. Must be non-nullable.
/// </typeparam>
/// <remarks>
/// Utilizes a provided generator function to produce unique keys of the specified type.
/// </remarks>
public class UniqueKeyGenerator<TKey>(Func<TKey> generator)
    where TKey : notnull
{
    /// <summary>
    /// Generates a unique key using the specified generator function.
    /// </summary>
    /// <returns>A unique key generated by the provided generator function.</returns>
    public TKey GenerateKey() => generator();
}