using System.Text.Json;
using Aesir.Modules.Research.Agents;
using Aesir.Modules.Research.Models;
using Microsoft.Extensions.Logging;

namespace Aesir.Modules.Research.Services;

/// <summary>
/// Service for generating and processing research clarification questions.
/// </summary>
public interface IClarificationService
{
    /// <summary>
    /// Generates clarifying questions for a research query using the Chairman agent.
    /// </summary>
    /// <param name="query">The original research query.</param>
    /// <param name="chairmanAgent">The Chairman agent to use for generation.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>List of clarifying questions, or empty if query is clear enough.</returns>
    Task<IReadOnlyList<string>> GenerateClarificationQuestionsAsync(
        string query,
        ResearchAgent chairmanAgent,
        CancellationToken cancellationToken = default);

    /// <summary>
    /// Refines a research query based on clarification answers.
    /// </summary>
    /// <param name="originalQuery">The original research query.</param>
    /// <param name="questions">The clarification questions that were asked.</param>
    /// <param name="answers">The user's answers to the questions.</param>
    /// <param name="chairmanAgent">The Chairman agent to use for refinement.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>The refined research query.</returns>
    Task<string> RefineQueryAsync(
        string originalQuery,
        IReadOnlyList<string> questions,
        IReadOnlyDictionary<string, string> answers,
        ResearchAgent chairmanAgent,
        CancellationToken cancellationToken = default);
}

/// <summary>
/// Implementation of the clarification service.
/// Note: Full chat integration will be added when wiring to the inference module.
/// </summary>
public class ClarificationService : IClarificationService
{
    private readonly ILogger<ClarificationService> _logger;

    public ClarificationService(ILogger<ClarificationService> logger)
    {
        _logger = logger;
    }

    /// <inheritdoc />
    public Task<IReadOnlyList<string>> GenerateClarificationQuestionsAsync(
        string query,
        ResearchAgent chairmanAgent,
        CancellationToken cancellationToken = default)
    {
        if (!chairmanAgent.IsChairman)
        {
            throw new ArgumentException("Clarification questions must be generated by the Chairman", nameof(chairmanAgent));
        }

        if (string.IsNullOrWhiteSpace(chairmanAgent.ClarificationPrompt))
        {
            _logger.LogWarning("Chairman agent has no clarification prompt");
            return Task.FromResult<IReadOnlyList<string>>([]);
        }

        _logger.LogInformation("Generating clarification questions for query: {QueryLength} characters", query.Length);

        // TODO: Integrate with IChatService when available
        // For now, return empty list (no clarification needed)
        // The actual implementation will use the chairman's ClarificationPrompt template
        // and call the inference engine to generate questions

        return Task.FromResult<IReadOnlyList<string>>([]);
    }

    /// <inheritdoc />
    public Task<string> RefineQueryAsync(
        string originalQuery,
        IReadOnlyList<string> questions,
        IReadOnlyDictionary<string, string> answers,
        ResearchAgent chairmanAgent,
        CancellationToken cancellationToken = default)
    {
        if (!chairmanAgent.IsChairman)
        {
            throw new ArgumentException("Query refinement must be done by the Chairman", nameof(chairmanAgent));
        }

        if (questions.Count == 0 || answers.Count == 0)
        {
            return Task.FromResult(originalQuery);
        }

        _logger.LogInformation("Refining query with {Count} clarification answers", answers.Count);

        // TODO: Integrate with IChatService when available
        // For now, append clarification context to the original query
        var refinedParts = new List<string> { originalQuery };

        foreach (var (question, answer) in answers)
        {
            refinedParts.Add($"Context: {question} - {answer}");
        }

        var refinedQuery = string.Join("\n", refinedParts);

        return Task.FromResult(refinedQuery);
    }

    /// <summary>
    /// Parses clarification questions from an LLM response.
    /// </summary>
    internal static List<string> ParseQuestionsFromResponse(string response)
    {
        var questions = new List<string>();

        // Try to find a JSON array in the response
        var startIndex = response.IndexOf('[');
        var endIndex = response.LastIndexOf(']');

        if (startIndex >= 0 && endIndex > startIndex)
        {
            var jsonPart = response.Substring(startIndex, endIndex - startIndex + 1);
            try
            {
                var parsed = JsonSerializer.Deserialize<List<string>>(jsonPart);
                if (parsed != null)
                {
                    questions.AddRange(parsed.Where(q => !string.IsNullOrWhiteSpace(q)));
                }
            }
            catch (JsonException)
            {
                // Fall through to alternative parsing
            }
        }

        // If JSON parsing failed, try to parse numbered questions
        if (questions.Count == 0)
        {
            var lines = response.Split('\n', StringSplitOptions.RemoveEmptyEntries);
            foreach (var line in lines)
            {
                var trimmed = line.Trim();
                // Look for numbered questions like "1. What..." or "- What..."
                if (trimmed.StartsWith("1.") || trimmed.StartsWith("2.") ||
                    trimmed.StartsWith("3.") || trimmed.StartsWith("4.") ||
                    trimmed.StartsWith("- ") || trimmed.StartsWith("* "))
                {
                    var question = trimmed.TrimStart('1', '2', '3', '4', '.', '-', '*', ' ');
                    if (!string.IsNullOrWhiteSpace(question) && question.Contains('?'))
                    {
                        questions.Add(question);
                    }
                }
            }
        }

        return questions;
    }
}
