using System.Text;
using System.Text.Json;
using Aesir.Common.Models;
using Aesir.Infrastructure.Services;
using Aesir.Modules.Research.Agents;
using Aesir.Modules.Research.Constants;
using Aesir.Modules.Research.Models;
using Microsoft.Extensions.Logging;

namespace Aesir.Modules.Research.Services;

/// <summary>
/// Service for generating and processing research clarification questions.
/// </summary>
public interface IClarificationService
{
    /// <summary>
    /// Generates clarifying questions for a research query using the Chairman agent.
    /// </summary>
    /// <param name="sessionId">The research session ID for SignalR updates.</param>
    /// <param name="query">The original research query.</param>
    /// <param name="chairmanAgent">The Chairman agent to use for generation.</param>
    /// <param name="chatSessionId">Optional chat session ID for inference log observability.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>List of clarifying questions, or empty if query is clear enough.</returns>
    Task<IReadOnlyList<string>> GenerateClarificationQuestionsAsync(
        Guid sessionId,
        string query,
        ResearchAgent chairmanAgent,
        Guid? chatSessionId = null,
        CancellationToken cancellationToken = default);

    /// <summary>
    /// Refines a research query based on clarification answers.
    /// </summary>
    /// <param name="sessionId">The research session ID for SignalR updates.</param>
    /// <param name="originalQuery">The original research query.</param>
    /// <param name="questions">The clarification questions that were asked.</param>
    /// <param name="answers">The user's answers to the questions.</param>
    /// <param name="chairmanAgent">The Chairman agent to use for refinement.</param>
    /// <param name="chatSessionId">Optional chat session ID for inference log observability.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>The refined research query.</returns>
    Task<string> RefineQueryAsync(
        Guid sessionId,
        string originalQuery,
        IReadOnlyList<string> questions,
        IReadOnlyDictionary<string, string> answers,
        ResearchAgent chairmanAgent,
        Guid? chatSessionId = null,
        CancellationToken cancellationToken = default);
}

/// <summary>
/// Implementation of the clarification service.
/// Uses IChatService for LLM-based clarification generation.
/// </summary>
public class ClarificationService : IClarificationService
{
    private readonly ILogger<ClarificationService> _logger;
    private readonly IChatServiceResolver _chatServiceResolver;
    private readonly IChatRequestBuilder _chatRequestBuilder;
    private readonly IResearchProgressBroadcaster _progressBroadcaster;

    public ClarificationService(
        ILogger<ClarificationService> logger,
        IChatServiceResolver chatServiceResolver,
        IChatRequestBuilder chatRequestBuilder,
        IResearchProgressBroadcaster progressBroadcaster)
    {
        _logger = logger;
        _chatServiceResolver = chatServiceResolver;
        _chatRequestBuilder = chatRequestBuilder;
        _progressBroadcaster = progressBroadcaster;
    }

    /// <inheritdoc />
    public async Task<IReadOnlyList<string>> GenerateClarificationQuestionsAsync(
        Guid sessionId,
        string query,
        ResearchAgent chairmanAgent,
        Guid? chatSessionId = null,
        CancellationToken cancellationToken = default)
    {
        if (!chairmanAgent.IsChairman)
        {
            throw new ArgumentException("Clarification questions must be generated by the Chairman", nameof(chairmanAgent));
        }

        if (string.IsNullOrWhiteSpace(chairmanAgent.ClarificationPrompt))
        {
            _logger.LogWarning("Chairman agent has no clarification prompt");
            return [];
        }

        _logger.LogInformation("Generating clarification questions for query: {QueryLength} characters", query.Length);

        // Notify phase change via broadcaster with active agent info
        await _progressBroadcaster.BroadcastProgressAsync(
            sessionId,
            ResearchPhase.Clarification,
            ResearchProgressMilestones.PhaseStart,
            "Chairman is analyzing the query for clarification needs...",
            new List<Contracts.ActiveAgentInfo>
            {
                new()
                {
                    TeamMemberId = chairmanAgent.TeamMemberId,
                    Role = chairmanAgent.Role,
                    RoleName = chairmanAgent.RoleName,
                    Activity = "Analyzing query...",
                    AgentProgressPercent = null
                }
            }).ConfigureAwait(false);

        // Get chat service for the Chairman
        var chatService = _chatServiceResolver.GetChatService(chairmanAgent.InferenceEngineId);

        if (chatService == null)
        {
            _logger.LogWarning("No chat service available for Chairman, skipping clarification");
            return [];
        }

        try
        {
            var response = await GenerateClarificationWithLlmAsync(
                sessionId, query, chairmanAgent, chatService, chatSessionId, cancellationToken).ConfigureAwait(false);

            // Parse questions from the response
            var questions = ParseQuestionsFromResponse(response);

            _logger.LogInformation("Generated {Count} clarification questions", questions.Count);
            return questions;
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "Failed to generate clarification questions via LLM");
            return [];
        }
    }

    /// <inheritdoc />
    public async Task<string> RefineQueryAsync(
        Guid sessionId,
        string originalQuery,
        IReadOnlyList<string> questions,
        IReadOnlyDictionary<string, string> answers,
        ResearchAgent chairmanAgent,
        Guid? chatSessionId = null,
        CancellationToken cancellationToken = default)
    {
        if (!chairmanAgent.IsChairman)
        {
            throw new ArgumentException("Query refinement must be done by the Chairman", nameof(chairmanAgent));
        }

        if (questions.Count == 0 || answers.Count == 0)
        {
            return originalQuery;
        }

        _logger.LogInformation("Refining query with {Count} clarification answers", answers.Count);

        // Notify phase change via broadcaster
        await _progressBroadcaster.BroadcastProgressAsync(
            sessionId,
            ResearchPhase.Clarification,
            ResearchProgressMilestones.LlmProcessing,
            "Chairman is refining the query with clarification answers...",
            new List<Contracts.ActiveAgentInfo>
            {
                new()
                {
                    TeamMemberId = chairmanAgent.TeamMemberId,
                    Role = chairmanAgent.Role,
                    RoleName = chairmanAgent.RoleName,
                    Activity = "Refining query...",
                    AgentProgressPercent = null
                }
            }).ConfigureAwait(false);

        // Get chat service for the Chairman
        var chatService = _chatServiceResolver.GetChatService(chairmanAgent.InferenceEngineId);

        if (chatService == null)
        {
            _logger.LogWarning("No chat service available for Chairman, using fallback refinement");
            return FallbackRefineQuery(originalQuery, questions, answers);
        }

        try
        {
            return await RefineQueryWithLlmAsync(
                sessionId, originalQuery, questions, answers, chairmanAgent, chatService, chatSessionId, cancellationToken).ConfigureAwait(false);
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "Failed to refine query via LLM, using fallback");
            return FallbackRefineQuery(originalQuery, questions, answers);
        }
    }

    /// <summary>
    /// Uses non-streaming LLM to generate clarification questions.
    /// </summary>
    private async Task<string> GenerateClarificationWithLlmAsync(
        Guid sessionId,
        string query,
        ResearchAgent chairmanAgent,
        IChatService chatService,
        Guid? chatSessionId,
        CancellationToken cancellationToken)
    {
        // Build the clarification prompt
        var userPrompt = BuildClarificationUserPrompt(query);

        var systemPrompt = chairmanAgent.ClarificationPrompt ?? """
            You are the Chairman of a research team. Before research begins, you analyze the user's query
            to determine if any clarifying questions would help focus the investigation.

            Good clarifying questions:
            - Help narrow overly broad topics
            - Resolve ambiguous terminology
            - Identify specific aspects of interest
            - Understand the context or purpose of the research

            Only ask questions if they would meaningfully improve the research. If the query is already
            clear and specific, indicate that no clarification is needed.
            """;

        var request = await _chatRequestBuilder.BuildAsync(
            chairmanAgent,
            systemPrompt,
            userPrompt,
            new ChatRequestOptions
            {
                IncludeTools = false,
                TemperatureOverride = 0.3,
                MaxTokensOverride = 1024,
                User = "research-clarification",
                Title = "Research Clarification",
                UseCustomPersona = true,
                ChatSessionId = chatSessionId
            }).ConfigureAwait(false);

        _logger.LogDebug("Sending clarification request to LLM (non-streaming)");

        // Use non-streaming call - simplified from streaming as part of progress system cleanup
        var result = await chatService.ChatCompletionsAsync(request).ConfigureAwait(false);

        // Extract the assistant's response
        var assistantMessage = result.AesirConversation?.Messages?
            .LastOrDefault(m => m.Role == "assistant");

        return assistantMessage?.Content ?? string.Empty;
    }

    /// <summary>
    /// Uses non-streaming LLM to refine the query based on answers.
    /// </summary>
    private async Task<string> RefineQueryWithLlmAsync(
        Guid sessionId,
        string originalQuery,
        IReadOnlyList<string> questions,
        IReadOnlyDictionary<string, string> answers,
        ResearchAgent chairmanAgent,
        IChatService chatService,
        Guid? chatSessionId,
        CancellationToken cancellationToken)
    {
        // Build the refinement prompt
        var userPrompt = BuildRefinementUserPrompt(originalQuery, questions, answers);

        var systemPrompt = """
            You are the Chairman of a research team. Your task is to refine a research query
            based on clarification answers provided by the user.

            Create a single, coherent, improved query that incorporates all the additional context.
            The refined query should be clear, specific, and actionable for the research team.
            """;

        var request = await _chatRequestBuilder.BuildAsync(
            chairmanAgent,
            systemPrompt,
            userPrompt,
            new ChatRequestOptions
            {
                IncludeTools = false,
                TemperatureOverride = 0.3,
                MaxTokensOverride = 2048,
                User = "research-refinement",
                Title = "Query Refinement",
                UseCustomPersona = true,
                ChatSessionId = chatSessionId
            }).ConfigureAwait(false);

        _logger.LogDebug("Sending query refinement request to LLM (non-streaming)");

        // Use non-streaming call - simplified from streaming as part of progress system cleanup
        var result = await chatService.ChatCompletionsAsync(request).ConfigureAwait(false);

        // Extract the assistant's response
        var assistantMessage = result.AesirConversation?.Messages?
            .LastOrDefault(m => m.Role == "assistant");

        var response = assistantMessage?.Content?.Trim() ?? string.Empty;

        // If the LLM returns a valid refined query, use it; otherwise return fallback
        if (!string.IsNullOrWhiteSpace(response) && response.Length > 10)
        {
            return response;
        }

        return FallbackRefineQuery(originalQuery, questions, answers);
    }

    /// <summary>
    /// Builds the user prompt for clarification generation.
    /// </summary>
    private static string BuildClarificationUserPrompt(string query)
    {
        return $"""
            ## Research Query
            {query}

            ## Your Task
            Analyze this research query and determine if any clarifying questions would help improve the research.

            If the query is clear and specific enough, respond with:
            ```json
            []
            ```

            If clarification would help, provide up to 4 questions as a JSON array:
            ```json
            ["Question 1?", "Question 2?", "Question 3?"]
            ```

            Focus on questions that would:
            - Narrow the scope if too broad
            - Clarify ambiguous terms
            - Identify specific aspects of interest
            - Understand the intended use of the research
            """;
    }

    /// <summary>
    /// Builds the user prompt for query refinement.
    /// </summary>
    private static string BuildRefinementUserPrompt(
        string originalQuery,
        IReadOnlyList<string> questions,
        IReadOnlyDictionary<string, string> answers)
    {
        var sb = new StringBuilder();
        sb.AppendLine("## Original Research Query");
        sb.AppendLine(originalQuery);
        sb.AppendLine();
        sb.AppendLine("## Clarification Q&A");

        for (var i = 0; i < questions.Count; i++)
        {
            var question = questions[i];
            answers.TryGetValue(question, out var answer);
            sb.AppendLine($"Q{i + 1}: {question}");
            sb.AppendLine($"A{i + 1}: {answer ?? "(no answer)"}");
            sb.AppendLine();
        }

        sb.AppendLine("## Your Task");
        sb.AppendLine("Based on the original query and the clarification answers, produce a refined research query.");
        sb.AppendLine("The refined query should:");
        sb.AppendLine("- Incorporate all relevant context from the answers");
        sb.AppendLine("- Be more specific and targeted than the original");
        sb.AppendLine("- Remain as a single, coherent query statement");
        sb.AppendLine();
        sb.AppendLine("Output ONLY the refined query text, nothing else.");

        return sb.ToString();
    }

    /// <summary>
    /// Fallback query refinement when LLM is not available.
    /// </summary>
    private static string FallbackRefineQuery(
        string originalQuery,
        IReadOnlyList<string> questions,
        IReadOnlyDictionary<string, string> answers)
    {
        var refinedParts = new List<string> { originalQuery };

        foreach (var question in questions)
        {
            if (answers.TryGetValue(question, out var answer) && !string.IsNullOrWhiteSpace(answer))
            {
                refinedParts.Add($"Context: {question} - {answer}");
            }
        }

        return string.Join("\n", refinedParts);
    }

    /// <summary>
    /// Parses clarification questions from an LLM response.
    /// </summary>
    internal static List<string> ParseQuestionsFromResponse(string response)
    {
        var questions = new List<string>();

        // Try to find a JSON array in the response
        var startIndex = response.IndexOf('[');
        var endIndex = response.LastIndexOf(']');

        if (startIndex >= 0 && endIndex > startIndex)
        {
            var jsonPart = response.Substring(startIndex, endIndex - startIndex + 1);
            try
            {
                var parsed = JsonSerializer.Deserialize<List<string>>(jsonPart);
                if (parsed != null)
                {
                    questions.AddRange(parsed.Where(q => !string.IsNullOrWhiteSpace(q)));
                }
            }
            catch (JsonException)
            {
                // Fall through to alternative parsing
            }
        }

        // If JSON parsing failed, try to parse numbered questions
        if (questions.Count == 0)
        {
            var lines = response.Split('\n', StringSplitOptions.RemoveEmptyEntries);
            foreach (var line in lines)
            {
                var trimmed = line.Trim();
                // Look for numbered questions like "1. What..." or "- What..."
                if (trimmed.StartsWith("1.") || trimmed.StartsWith("2.") ||
                    trimmed.StartsWith("3.") || trimmed.StartsWith("4.") ||
                    trimmed.StartsWith("- ") || trimmed.StartsWith("* "))
                {
                    var question = trimmed.TrimStart('1', '2', '3', '4', '.', '-', '*', ' ');
                    if (!string.IsNullOrWhiteSpace(question) && question.Contains('?'))
                    {
                        questions.Add(question);
                    }
                }
            }
        }

        return questions;
    }
}
