using Aesir.Infrastructure.Documents;
using Aesir.Modules.Research.Models;
using Microsoft.Extensions.Logging;
using DocFormat = Aesir.Infrastructure.Documents.DocumentFormat;

namespace Aesir.Modules.Research.Services;

/// <summary>
/// Service for exporting research reports to various document formats.
/// </summary>
public interface IResearchReportExporter
{
    /// <summary>
    /// Exports a research report to the specified format.
    /// </summary>
    /// <param name="report">The research report to export.</param>
    /// <param name="format">The target document format.</param>
    /// <param name="cancellationToken">Cancellation token.</param>
    /// <returns>The export result containing the document bytes.</returns>
    Task<ExportResult> ExportAsync(
        ResearchReport report,
        DocFormat format,
        CancellationToken cancellationToken = default);

    /// <summary>
    /// Gets the available export formats.
    /// </summary>
    IEnumerable<DocFormat> GetAvailableFormats();
}

/// <summary>
/// Implementation of the research report exporter.
/// </summary>
public class ResearchReportExporter : IResearchReportExporter
{
    private readonly ILogger<ResearchReportExporter> _logger;
    private readonly IDocumentExporterFactory _exporterFactory;

    public ResearchReportExporter(
        ILogger<ResearchReportExporter> logger,
        IDocumentExporterFactory exporterFactory)
    {
        _logger = logger;
        _exporterFactory = exporterFactory;
    }

    /// <inheritdoc />
    public async Task<ExportResult> ExportAsync(
        ResearchReport report,
        DocFormat format,
        CancellationToken cancellationToken = default)
    {
        _logger.LogInformation(
            "Exporting research report {ReportId} to {Format}",
            report.Id,
            format);

        try
        {
            // Convert ResearchReport to generic ExportDocument
            var document = ConvertToExportDocument(report);

            // Get the appropriate exporter
            var exporter = _exporterFactory.GetExporter(format);

            // Export the document
            var result = await exporter.ExportAsync(document, cancellationToken);

            if (result.Success)
            {
                _logger.LogInformation(
                    "Successfully exported report {ReportId} to {Format}. Size: {Size} bytes",
                    report.Id,
                    format,
                    result.Data?.Length ?? 0);
            }
            else
            {
                _logger.LogWarning(
                    "Failed to export report {ReportId} to {Format}: {Error}",
                    report.Id,
                    format,
                    result.ErrorMessage);
            }

            return result;
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "Error exporting report {ReportId} to {Format}", report.Id, format);
            return ExportResult.Failed($"Export failed: {ex.Message}");
        }
    }

    /// <inheritdoc />
    public IEnumerable<DocFormat> GetAvailableFormats()
    {
        return _exporterFactory.GetAllExporters().Select(e => e.Format);
    }

    /// <summary>
    /// Converts a ResearchReport to the generic ExportDocument format.
    /// </summary>
    private ExportDocument ConvertToExportDocument(ResearchReport report)
    {
        var document = new ExportDocument
        {
            Title = report.Title,
            Subtitle = "Research Report",
            Author = "Aesir Research Team",
            CreatedAt = report.CreatedAt,
            IncludePageNumbers = true,
            FooterText = "Generated by Aesir Research Mode",
            Sections = []
        };

        // Add metadata to document
        if (report.Metadata != null)
        {
            document.Metadata = new Dictionary<string, string>
            {
                ["Duration"] = FormatDuration(report.Metadata.TotalDurationMs),
                ["TotalTokens"] = report.Metadata.TotalTokensUsed.ToString("N0"),
                ["Sources"] = report.Metadata.SourceCount.ToString(),
                ["Findings"] = report.Metadata.FindingCount.ToString(),
                ["AvgPeerReviewScore"] = report.Metadata.AveragePeerReviewScore.ToString("F1")
            };
        }

        // Executive Summary section
        if (!string.IsNullOrWhiteSpace(report.ExecutiveSummary))
        {
            document.Sections.Add(new DocumentSection
            {
                Heading = "Executive Summary",
                HeadingLevel = 1,
                Content =
                [
                    new MarkdownContent { Markdown = report.ExecutiveSummary }
                ]
            });
        }

        // Methodology section
        if (!string.IsNullOrWhiteSpace(report.MethodologySection))
        {
            document.Sections.Add(new DocumentSection
            {
                Heading = "Methodology",
                HeadingLevel = 1,
                PageBreakBefore = true,
                Content =
                [
                    new MarkdownContent { Markdown = report.MethodologySection }
                ]
            });
        }

        // Key Findings section
        if (report.Findings?.Count > 0)
        {
            var findingsSection = new DocumentSection
            {
                Heading = "Key Findings",
                HeadingLevel = 1,
                PageBreakBefore = true,
                Content = []
            };

            foreach (var finding in report.Findings)
            {
                // Finding title with confidence indicator
                var confidenceLabel = GetConfidenceLabel(finding.Confidence);
                findingsSection.Content.Add(new ParagraphContent
                {
                    Text = $"{finding.Title} [{confidenceLabel}]",
                    Bold = true
                });

                // Finding content
                findingsSection.Content.Add(new MarkdownContent
                {
                    Markdown = finding.Content
                });

                // Supporting evidence
                if (finding.SupportingEvidence?.Count > 0)
                {
                    findingsSection.Content.Add(new ParagraphContent
                    {
                        Text = "Supporting Evidence:",
                        Italic = true
                    });

                    findingsSection.Content.Add(new ListContent
                    {
                        Items = finding.SupportingEvidence.ToList(),
                        Ordered = false
                    });
                }

                // Sources for this finding
                if (finding.Sources?.Count > 0)
                {
                    findingsSection.Content.Add(new ParagraphContent
                    {
                        Text = "Sources:",
                        Italic = true
                    });

                    findingsSection.Content.Add(new ListContent
                    {
                        Items = finding.Sources.Select(s => FormatSource(s)).ToList(),
                        Ordered = true
                    });
                }
            }

            document.Sections.Add(findingsSection);
        }

        // Alternative Perspectives section
        if (!string.IsNullOrWhiteSpace(report.AlternativePerspectives))
        {
            document.Sections.Add(new DocumentSection
            {
                Heading = "Alternative Perspectives",
                HeadingLevel = 1,
                PageBreakBefore = true,
                Content =
                [
                    new MarkdownContent { Markdown = report.AlternativePerspectives }
                ]
            });
        }

        // Research Gaps section
        if (!string.IsNullOrWhiteSpace(report.ResearchGaps))
        {
            document.Sections.Add(new DocumentSection
            {
                Heading = "Research Gaps",
                HeadingLevel = 1,
                Content =
                [
                    new MarkdownContent { Markdown = report.ResearchGaps }
                ]
            });
        }

        // Bibliography section
        if (report.Bibliography?.Count > 0)
        {
            var bibliographySection = new DocumentSection
            {
                Heading = "Bibliography",
                HeadingLevel = 1,
                PageBreakBefore = true,
                Content =
                [
                    new ListContent
                    {
                        Items = report.Bibliography.Select(s => FormatBibliographyEntry(s)).ToList(),
                        Ordered = true
                    }
                ]
            };

            document.Sections.Add(bibliographySection);
        }

        // Appendix: Research Metadata
        if (report.Metadata != null)
        {
            var metadataSection = new DocumentSection
            {
                Heading = "Appendix: Research Metadata",
                HeadingLevel = 1,
                PageBreakBefore = true,
                Content = []
            };

            // Create metadata table
            var tableHeaders = new List<string> { "Metric", "Value" };
            var tableRows = new List<List<string>>
            {
                new() { "Total Duration", FormatDuration(report.Metadata.TotalDurationMs) },
                new() { "Total Tokens Used", report.Metadata.TotalTokensUsed.ToString("N0") },
                new() { "Sources Cited", report.Metadata.SourceCount.ToString() },
                new() { "Findings Generated", report.Metadata.FindingCount.ToString() },
                new() { "Average Peer Review Score", $"{report.Metadata.AveragePeerReviewScore:F1}/10" }
            };

            metadataSection.Content.Add(new TableContent
            {
                Headers = tableHeaders,
                Rows = tableRows
            });

            // Agent statistics
            if (report.Metadata.AgentStatistics?.Count > 0)
            {
                metadataSection.Content.Add(new ParagraphContent
                {
                    Text = "Agent Contributions:",
                    Bold = true
                });

                var agentHeaders = new List<string> { "Agent", "Role", "Tokens", "Duration", "Sources", "Avg Review" };
                var agentRows = report.Metadata.AgentStatistics.Select(kvp => new List<string>
                {
                    kvp.Key,
                    kvp.Value.Role.ToString(),
                    kvp.Value.TokensUsed.ToString("N0"),
                    FormatDuration(kvp.Value.DurationMs),
                    kvp.Value.SourcesCited.ToString(),
                    $"{kvp.Value.AverageReviewScore:F1}"
                }).ToList();

                metadataSection.Content.Add(new TableContent
                {
                    Headers = agentHeaders,
                    Rows = agentRows
                });
            }

            document.Sections.Add(metadataSection);
        }

        return document;
    }

    private static string GetConfidenceLabel(ConfidenceLevel confidence) => confidence switch
    {
        ConfidenceLevel.High => "High Confidence",
        ConfidenceLevel.Medium => "Medium Confidence",
        ConfidenceLevel.Low => "Low Confidence",
        _ => "Unknown"
    };

    private static string FormatDuration(long milliseconds)
    {
        var timeSpan = TimeSpan.FromMilliseconds(milliseconds);

        if (timeSpan.TotalHours >= 1)
            return $"{timeSpan.Hours}h {timeSpan.Minutes}m {timeSpan.Seconds}s";

        if (timeSpan.TotalMinutes >= 1)
            return $"{timeSpan.Minutes}m {timeSpan.Seconds}s";

        return $"{timeSpan.Seconds}s";
    }

    private static string FormatSource(ResearchSource source)
    {
        var parts = new List<string>();

        if (!string.IsNullOrEmpty(source.Title))
            parts.Add(source.Title);

        if (!string.IsNullOrEmpty(source.SourceType))
            parts.Add($"[{source.SourceType}]");

        if (!string.IsNullOrEmpty(source.Url))
            parts.Add($"({source.Url})");

        return string.Join(" ", parts);
    }

    private static string FormatBibliographyEntry(ResearchSource source)
    {
        var entry = new System.Text.StringBuilder();

        if (!string.IsNullOrEmpty(source.Title))
        {
            entry.Append('"');
            entry.Append(source.Title);
            entry.Append('"');
            entry.Append(". ");
        }

        if (!string.IsNullOrEmpty(source.SourceType))
        {
            entry.Append('[');
            entry.Append(source.SourceType);
            entry.Append("] ");
        }

        if (!string.IsNullOrEmpty(source.Url))
        {
            entry.Append("Available at: ");
            entry.Append(source.Url);
        }

        if (!string.IsNullOrEmpty(source.Quote))
        {
            entry.Append(" - \"");
            entry.Append(source.Quote.Length > 100 ? source.Quote[..100] + "..." : source.Quote);
            entry.Append('"');
        }

        return entry.ToString().TrimEnd();
    }
}
